# Cloud Build configuration for deploying to Cloud Run
# =====================================================
# Deploy with: gcloud builds submit --config=cloudbuild.yaml
#
# Prerequisites:
# 1. Enable Cloud Build and Cloud Run APIs
# 2. Configure service account permissions

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ixia-inventory-explorer:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ixia-inventory-explorer:latest'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/ixia-inventory-explorer:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/ixia-inventory-explorer:latest'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'ixia-inventory-explorer'
      - '--image'
      - 'gcr.io/$PROJECT_ID/ixia-inventory-explorer:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '300'
      - '--concurrency'
      - '80'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'

images:
  - 'gcr.io/$PROJECT_ID/ixia-inventory-explorer:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/ixia-inventory-explorer:latest'

substitutions:
  _REGION: 'us-central1'  # Change to your preferred region

timeout: '1800s'  # 30 minute timeout for build

